name: protect
description: Protect protects excel files with password and also helps to decrypt the password protected excel files
version: 0.0.1
homepage: https://github.com/justkawal/protect

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  xml_parser: ^0.1.2
  crypto: ^2.1.5
  utf: ^0.9.0+5
  aes_crypt: ^0.1.1
