name: protect
description: Protect encrypts/decrypt your excel files with password.
version: 1.0.0
homepage: https://github.com/justkawal/protect

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  xml_parser: ^1.0.0
  crypto: ^3.0.1
  aes_crypt_null_safe: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
